# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fc9e4b9e6731949bed237f86fdac2e5456bf585378aec38d57bf7473167db1d02fe389bf3a116b85eebbbe05d7d614a0948d453acf3a2b110e823bca3043029

test:
  secret_key_base: 5adc0ca2e1acb6ac6d18c13c7bb77524f0efc5ed608ff64da08e1793d8c87cdad2986c281f657a164b2bf33d49e0a6714332b0f37758d1c41d1656aae43238e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
